const dummyHistory = [{
   "TrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720304825423",
   "Tax": 0,
   "ShippingStreet": "1001\n14th St NW",
   "ShippingStateCode": "WA",
   "ShippingState": "Washington",
   "ShippingPostalCode": "98826",
   "ShippingCountryCode": "USA",
   "ShippingCountry": "United States",
   "ShippingContactName": "MAHESH Kotapali",
   "ShippingCity": "Washington DC",
   "ShippingAmount": 0,
   "ShippedDate": "2021-08-06T08:44:00.000Z",
   "PaymentMethod": "CreditCard",
   "OrderStatus": "Shipped",
   "OrderNumber": "631785",
   "OrderGrandTotal": 33.9,
   "OrderCreatedDate": "2021-08-06T08:44:00.000Z",
   "Items": [{
      "Weight": "12 OZ",
      "VendorName": "Klatch",
      "UnitPrice": 16.95,
      "TotalPrice": 33.9,
      "SubscriptionFrequency": "2 Weeks",
      "Quantity": 2,
      "Promocode": null,
      "ProductNumber": "MBZ31188CWA02012Z",
      "ProductImageUrl": "https://www.beanz.com/content/dam/marketplace/us/assets/VEN31188/mbz31188cwa02012z/pdp.jpg",
      "ItemTrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720304825423",
      "ItemTax": 0,
      "ItemStatus": "Shipped",
      "ItemSequence": 1,
      "ItemDescription": "Summer WBC World's Best Espresso",
      "IsSubscriptionItem": true,
      "IsMysteryItem": false,
      "GrindType": "Whole bean",
      "EPStandingOrderId": "747",
      "DisplayAsMysteryItem": false,
      "DiscountPercentage": 0,
      "Discount": 0,
      "CoffeeType": "Blend"
   }],
   "HasSubscriptions": true,
   "CurrencyCode": "USD",
   "CancelDate": null,
   "BillingStreet": "1001\n14th St NW",
   "BillingStateCode": "WA",
   "BillingState": "Washington",
   "BillingPostalCode": "98826",
   "BillingCountryCode": "United States",
   "BillingCountry": "United States",
   "BillingContactName": 'Paul',
   "BillingCity": "Washington DC"
},
{
   "TrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720322055383",
   "Tax": 0,
   "ShippingStreet": "1001\n14th St NW",
   "ShippingStateCode": "WA",
   "ShippingState": "Washington",
   "ShippingPostalCode": "98826",
   "ShippingCountryCode": "USA",
   "ShippingCountry": "United States",
   "ShippingContactName": "MAHESH Kotapali",
   "ShippingCity": "Washington DC",
   "ShippingAmount": 0,
   "ShippedDate": null,
   "PaymentMethod": "CreditCard",
   "OrderStatus": "Shipped",
   "OrderNumber": "621182",
   "OrderGrandTotal": 33.9,
   "OrderCreatedDate": "2021-07-23T08:03:41.000Z",
   "Items": [{
      "Weight": "12 OZ",
      "VendorName": "Klatch",
      "UnitPrice": 16.95,
      "TotalPrice": 33.9,
      "SubscriptionFrequency": "2 Weeks",
      "Quantity": 2,
      "Promocode": null,
      "ProductNumber": "MBZ31188CWA02012Z",
      "ProductImageUrl": "https://www.beanz.com/content/dam/marketplace/us/assets/VEN31188/mbz31188cwa02012z/pdp.jpg",
      "ItemTrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720322055383",
      "ItemTax": 0,
      "ItemStatus": "Shipped",
      "ItemSequence": 1,
      "ItemDescription": "Summer WBC World's Best Espresso",
      "IsSubscriptionItem": true,
      "IsMysteryItem": false,
      "GrindType": "Whole bean",
      "EPStandingOrderId": "2762",
      "DisplayAsMysteryItem": false,
      "DiscountPercentage": 0,
      "Discount": 0,
      "CoffeeType": "Blend"
   }],
   "HasSubscriptions": true,
   "CurrencyCode": "USD",
   "CancelDate": null,
   "BillingStreet": "1001\n14th St NW",
   "BillingStateCode": "WA",
   "BillingState": "Washington",
   "BillingPostalCode": "98826",
   "BillingCountryCode": "United States",
   "BillingCountry": "United States",
   "BillingContactName": null,
   "BillingCity": "Washington DC"
},
{
   "TrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720312750382",
   "Tax": 0,
   "ShippingStreet": "1001\n14th St NW",
   "ShippingStateCode": "WA",
   "ShippingState": "Washington",
   "ShippingPostalCode": "98826",
   "ShippingCountryCode": "USA",
   "ShippingCountry": "United States",
   "ShippingContactName": "MAHESH Kotapali",
   "ShippingCity": "Washington DC",
   "ShippingAmount": 0,
   "ShippedDate": null,
   "PaymentMethod": "CreditCard",
   "OrderStatus": "Shipped",
   "OrderNumber": "608889",
   "OrderGrandTotal": 33.9,
   "OrderCreatedDate": "2021-07-09T08:03:47.000Z",
   "Items": [{
      "Weight": "12 OZ",
      "VendorName": "Klatch",
      "UnitPrice": 16.95,
      "TotalPrice": 33.9,
      "SubscriptionFrequency": "2 Weeks",
      "Quantity": 2,
      "Promocode": null,
      "ProductNumber": "MBZ31188CWA02012Z",
      "ProductImageUrl": "https://www.beanz.com/content/dam/marketplace/us/assets/VEN31188/mbz31188cwa02012z/pdp.jpg",
      "ItemTrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720312750382",
      "ItemTax": 0,
      "ItemStatus": "Shipped",
      "ItemSequence": 1,
      "ItemDescription": "Summer WBC World's Best Espresso",
      "IsSubscriptionItem": true,
      "IsMysteryItem": false,
      "GrindType": "Whole bean",
      "EPStandingOrderId": "2762",
      "DisplayAsMysteryItem": false,
      "DiscountPercentage": 0,
      "Discount": 0,
      "CoffeeType": "Blend"
   }],
   "HasSubscriptions": true,
   "CurrencyCode": "USD",
   "CancelDate": null,
   "BillingStreet": "1001\n14th St NW",
   "BillingStateCode": "WA",
   "BillingState": "Washington",
   "BillingPostalCode": "98826",
   "BillingCountryCode": "United States",
   "BillingCountry": "United States",
   "BillingContactName": null,
   "BillingCity": "Washington DC"
},
{
   "TrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720322537086",
   "Tax": 0,
   "ShippingStreet": "1001\n14th St NW",
   "ShippingStateCode": "WA",
   "ShippingState": "Washington",
   "ShippingPostalCode": "98826",
   "ShippingCountryCode": "USA",
   "ShippingCountry": "United States",
   "ShippingContactName": "MAHESH Kotapali",
   "ShippingCity": "Washington DC",
   "ShippingAmount": 0,
   "ShippedDate": null,
   "PaymentMethod": "CreditCard",
   "OrderStatus": "Shipped",
   "OrderNumber": "475280",
   "OrderGrandTotal": 33.9,
   "OrderCreatedDate": "2021-02-05T08:04:19.000Z",
   "Items": [{
      "Weight": "12 OZ",
      "VendorName": "Klatch",
      "UnitPrice": 16.95,
      "TotalPrice": 33.9,
      "SubscriptionFrequency": "2 Weeks",
      "Quantity": 2,
      "Promocode": null,
      "ProductNumber": "MBZ31188CWA02012Z",
      "ProductImageUrl": "https://www.beanz.com/content/dam/marketplace/us/assets/VEN31188/mbz31188cwa02012z/pdp.jpg",
      "ItemTrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720322537086",
      "ItemTax": 0,
      "ItemStatus": "Shipped",
      "ItemSequence": 1,
      "ItemDescription": "Summer WBC World's Best Espresso",
      "IsSubscriptionItem": true,
      "IsMysteryItem": false,
      "GrindType": "Whole bean",
      "EPStandingOrderId": "2762",
      "DisplayAsMysteryItem": false,
      "DiscountPercentage": 0,
      "Discount": 0,
      "CoffeeType": "Blend"
   }],
   "HasSubscriptions": true,
   "CurrencyCode": "USD",
   "CancelDate": null,
   "BillingStreet": "1001\n14th St NW",
   "BillingStateCode": "WA",
   "BillingState": "Washington",
   "BillingPostalCode": "98826",
   "BillingCountryCode": "United States",
   "BillingCountry": "United States",
   "BillingContactName": null,
   "BillingCity": "Washington DC"
},
{
   "TrackingLink": null,
   "Tax": 0,
   "ShippingStreet": "1001\n14th St NW",
   "ShippingStateCode": "WA",
   "ShippingState": "Washington",
   "ShippingPostalCode": "98826",
   "ShippingCountryCode": "USA",
   "ShippingCountry": "United States",
   "ShippingContactName": "MAHESH Kotapali",
   "ShippingCity": "Washington DC",
   "ShippingAmount": 0,
   "ShippedDate": null,
   "PaymentMethod": "CreditCard",
   "OrderStatus": "Shipped",
   "OrderNumber": "445402",
   "OrderGrandTotal": 33.9,
   "OrderCreatedDate": "2021-01-21T08:50:48.000Z",
   "Items": [{
      "Weight": "12 OZ",
      "VendorName": "Klatch",
      "UnitPrice": 16.95,
      "TotalPrice": 33.9,
      "SubscriptionFrequency": "2 Weeks",
      "Quantity": 2,
      "Promocode": null,
      "ProductNumber": "MBZ31188CWA02012Z",
      "ProductImageUrl": "https://www.beanz.com/content/dam/marketplace/us/assets/VEN31188/mbz31188cwa02012z/pdp.jpg",
      "ItemTrackingLink": "https://wwwapps.ups.com/WebTracking/track?loc=en_US&track.x=Track&trackNums=1ZEA55720316856029",
      "ItemTax": 0,
      "ItemStatus": "Shipped",
      "ItemSequence": 1,
      "ItemDescription": "Summer WBC World's Best Espresso",
      "IsSubscriptionItem": true,
      "IsMysteryItem": false,
      "GrindType": "Whole bean",
      "EPStandingOrderId": "2762",
      "DisplayAsMysteryItem": false,
      "DiscountPercentage": 0,
      "Discount": 0,
      "CoffeeType": "Blend"
   }],
   "HasSubscriptions": true,
   "CurrencyCode": "USD",
   "CancelDate": null,
   "BillingStreet": "1001\n14th St NW",
   "BillingStateCode": "WA",
   "BillingState": "Washington",
   "BillingPostalCode": "98826",
   "BillingCountryCode": "United States",
   "BillingCountry": "United States",
   "BillingContactName": null,
   "BillingCity": "Washington DC"
}
]

export default dummyHistory;